// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNR7yEDm_LS25vdOlFw17cM92-UzpWkE',
    appId: '1:461373675112:web:e885637b4efd065e820ddd',
    messagingSenderId: '461373675112',
    projectId: 'lotto168-app',
    authDomain: 'lotto168-app.firebaseapp.com',
    storageBucket: 'lotto168-app.appspot.com',
    measurementId: 'G-C30LE4TYH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX4usYJgaege8pZo8QgZDIUUwq_eth_bo',
    appId: '1:461373675112:android:04b6586dc1d9800b820ddd',
    messagingSenderId: '461373675112',
    projectId: 'lotto168-app',
    storageBucket: 'lotto168-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMeLCgbHwnPKg-iiP3bq15JVr_SJzfso',
    appId: '1:461373675112:ios:3cab9c4761997be7820ddd',
    messagingSenderId: '461373675112',
    projectId: 'lotto168-app',
    storageBucket: 'lotto168-app.appspot.com',
    iosBundleId: 'com.example.miniprojectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzMeLCgbHwnPKg-iiP3bq15JVr_SJzfso',
    appId: '1:461373675112:ios:3cab9c4761997be7820ddd',
    messagingSenderId: '461373675112',
    projectId: 'lotto168-app',
    storageBucket: 'lotto168-app.appspot.com',
    iosBundleId: 'com.example.miniprojectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqNR7yEDm_LS25vdOlFw17cM92-UzpWkE',
    appId: '1:461373675112:web:28d115d016227672820ddd',
    messagingSenderId: '461373675112',
    projectId: 'lotto168-app',
    authDomain: 'lotto168-app.firebaseapp.com',
    storageBucket: 'lotto168-app.appspot.com',
    measurementId: 'G-2Y6LPNST2C',
  );
}
